### ISSUE TITLE
platform flag does not appear to compile all resources correctly

### ISSUE THREAD

**Issue by tylervick** [ali5h/rules_pip#12]
Hello,

I'm attempting to use the grpc library that depends on a built-in cython package. This appears to fail to build even when pip_install is passed the platform flag (`pip_install(["--platform=linux_x86_64"]`).

```
  File "/app/qa_configurator/qa_configurator.binary.runfiles/pypi__38__google_api_core_1_16_0/google/api_core/gapic_v1/config.py", line 23, in <module>
    import grpc
  File "/app/qa_configurator/qa_configurator.binary.runfiles/pypi__38__grpcio_1_23_0/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/app/qa_configurator/qa_configurator.binary.runfiles/pypi__38__grpcio_1_23_0/grpc/_cython/__init__.py)
```

I'm not sure if this is due to grpc using an internal dependency or not. I'm curious if there are any workarounds to this. Thanks!

**Comment by ali5h** [comment]
you should use `pip_install(["--platform", "manylinux1_x86_64"]`. Also check python version in the docker image. I will add an example
