### ISSUE TITLE
failed to download python packages listed in the requirements3.txt

### ISSUE THREAD

**Issue by deryck1031** [ali5h/rules_pip#2]
We are behind a proxy and have https_proxy set already.  We are using your WORKSPACE for building, only thing we changed was the python version (3.7).  Below is our BUILD file:

load("@piptool_deps_3//:requirements.bzl", "requirement")
py_library(
    name = "greeting",
    srcs = ["greeting.py"],
   deps=[requirement("six"), ]
)

We are getting below errors:

ERROR: An error occurred during the fetch of repository 'pypi__3_7__six_1_12_0':
   whl_library failed:  (Could not find a version that satisfies the requirement six==1.12.0 (from -c /home/user/.cache/bazel/_bazel_zkf2           07m/95f94b938bcb1f4d30d7174b72ea61e0/external/piptool_deps_3/requirements.txt (line 10)) (from versions: none) 
pip._internal.exceptions.DistributionNotFound: No matching distribution found for six==1.12.0 (from -c /home/user/.cache/bazel/_bazel_zkf           207m/95f94b938bcb1f4d30d7174b72ea61e0/external/piptool_deps_3/requirements.txt (line 10))

**Comment by ali5h** [comment]
do you have a requirement in ur project, how r u using this repo?

**Comment by ali5h** [comment]
try to add https_proxy through `action_env`
