### ISSUE TITLE
Please document example of namespace handling

### ISSUE THREAD

**Issue by chickenandpork** [ali5h/rules_pip#35]
Hey @ali5h, I've got an instance of the google.* and azure.* namespace clash issue (bazelbuild/rules_python#93 bazelbuild/rules_python#55).  You've indicated that you fixed it, but the problem still persists in `v2.1.1`, can you give an idea of what that fix looks like?

https://github.com/bazelbuild/rules_python/issues/93#issuecomment-533837325
> i fixed this issue in https://github.com/ali5h/rules_pip

as well https://github.com/bazelbuild/rules_python/issues/93#issuecomment-565391286
> fixed the issues, plz use latest release, thanks for the feedback

I'm using your latest release, and I'm still seeing the issue.  Maybe there's additional text I've missed describing what else to do to activate this repair.

If you see https://github.com/chickenandpork/bazel-pip-import-namespace, it represents the issue I'm having.  Note that transitory dependencies were tried as well, then commented back out in the `BUILD` file.

`bazel test //...` repro the error.

I believe this follows the instructions you've shared. Can you see what else is missing to work around the issue ?

**Comment by ali5h** [comment]
i will check, but in the meanwhile look in `examples`

**Comment by ali5h** [comment]
it passes for me, on mac, python 3.8

**Comment by ali5h** [comment]
also tested on linux

**Comment by chickenandpork** [comment]
I appreciate your quick reply.

Can you confirm it is not leveraging your locally-installed packages?

I found the issue is avoided and the build passes if either package is locally-installed on my build system and available on PYTHONPATH (ie not brought in hermetically by Bazel).  Locally-installed non-hermetic packages are not the intention though.

**Comment by ali5h** [comment]
they are not

**Comment by ali5h** [comment]
it would be great if you can add Dockerfile to reproduce this

**Comment by chickenandpork** [comment]
Looks like I'm wrong; Sorry.

Your very specific request (thanks) helped me find a possible solution (build host taint trashing the first resolution of the `google.*` namespace, and failing, so no others checked.

Bazel builds should be hermetic !

 * pip list | grep google
 * pip uninstall {the google things}

For the next person who has this issue (and for when I forget :-/ ) I'm documenting the path to the solution at https://github.com/chickenandpork/bazel-pip-import-namespace#recommendation
