### ISSUE TITLE
Feature request: Allow custom BUILD file content to be appended to generated BUILD.

### ISSUE THREAD

**Issue by sohaibiftikhar** [ali5h/rules_pip#40]
For some python modules that depend on shared libraries written in C++ such as Tensorflow sometimes it is necessary to allow declaration of targets a bit differently. Or to add additional targets such as filegroups. Currently this is not customizable through `rules_pip`. It would be nice to allow this using an additional parameter to the `pip_import` rule.

**Comment by sohaibiftikhar** [comment]
@ali5h Is this the same as #6 ?

**Comment by ali5h** [comment]
yes

**Comment by sohaibiftikhar** [comment]
Closing this in favour of #6
