### ISSUE TITLE
Usage of `python_configure`

### ISSUE THREAD

**Issue by cwaeland** [ali5h/rules_pip#49]
Me once again.

I was taking a look at your examples directory and noticed the usage of `python_configure` in your WORKSPACE file.  I have not been making use of this and it seems as though things are working correctly.  Just wanted to confirm if this was something I should be making use of.

I've been experimenting with configuring my own python toolchain and this seems possibly related.

Thanks.

**Comment by ali5h** [comment]
it is usable, i need to push some changes to make it more robust, py3 extensions created this way have suffixes, which now i think should not be the case
