### ISSUE TITLE
Bazel Python rules maintainership collaboration

### ISSUE THREAD

**Issue by thundergolfer** [ali5h/rules_pip#56]
👋  maintainer of [github.com/bazelbuild/rules_python](https://github.com/bazelbuild/rules_python) here.

I reached to @ali5h on the Bazel community Slack workspace, but I'm not sure they're hanging around there. 

I think it would be good for the maintainers in rules_python to be in touch regularly with the maintainers in this repo, and work together to make there be 'one way' to do Python `pip` stuff in Bazel. 

Working together would be particularly useful in situations related to this issue, https://github.com/bazelbuild/rules_python/issues/395, where this repository has some functionality that's useful and _not_ present in rules_python.

**Comment by thundergolfer** [comment]
If you want to get in touch, I'll of course be available in this thread, but you can also reach me over in the Bazel Slack or contact me via email at `<first name> at <company name> dot com`.

**Comment by ali5h** [comment]
I am available, how can I help?

**Comment by thundergolfer** [comment]
We're in touch in Slack, so I can post over there 👍 . Feel free to close the issue now.
